image: fedora:latest

before_script:
  - dnf update -y
  - dnf install -y acl gawk which fakeroot rpm-build wget fedpkg gcc gcc-c++ make
  - umask 0022

build_rpm:
  stage: build
  script:
    - wget https://api.github.com/repos/GrapheneOS/hardened_malloc/tarball/2026050400
    - echo "ce713fd74b684b24ab1ce25a763dbb0ddb700c9109e01e756e9c6e92ab60476b293f8b723041a1ea842d12584e541cf30f72401c98cdcda49d6a9f60d548cfd6  2026050400" | sha512sum -c
    - fedpkg --release f44 local
  artifacts:
    paths:
        - x86_64/hardened_malloc*.x86_64.rpm
        - hardened_malloc*.src.rpm
