image: fedora:latest

before_script:
  - dnf update -y
  - dnf install -y acl gawk which fakeroot rpm-build wget fedpkg gcc gcc-c++ make
  - umask 0022

build_rpm:
  stage: build
  script:
    - wget https://api.github.com/repos/GrapheneOS/hardened_malloc/tarball/2026030100
    - echo "c6eca3e3666973dd7d40ee24002c5d4532ce5a96d134a1d81f646501ca822384f35be1725ab2cb727de50e3eafc136e48b016de06bb80de9c08e82062ebdc7b2  2026030100" | sha512sum -c
    - fedpkg --release f43 local
  artifacts:
    paths:
        - x86_64/hardened_malloc*.x86_64.rpm
        - hardened_malloc*.src.rpm
