image: fedora:latest

before_script:
  - dnf update -y
  - dnf install -y acl gawk which fakeroot rpm-build wget fedpkg gcc gcc-c++ make
  - umask 0022

build_rpm:
  stage: build
  script:
    - wget https://api.github.com/repos/GrapheneOS/hardened_malloc/tarball/2026060100
    - echo "eda250ffa8a525e1ae93060c5bfe4f1956689b20b2141279647a110442e54d965bc820b4298d4c7ab45a8ffbbe1f0a3547f46683671c47c7095c7ada93318603  2026060100" | sha512sum -c
    - fedpkg --release f44 local
  artifacts:
    paths:
        - x86_64/hardened_malloc*.x86_64.rpm
        - hardened_malloc*.src.rpm
